# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lequan/workspace/xcode/myopencv/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lequan/workspace/xcode/myopencv/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lequan/workspace/xcode/myopencv/src/CMakeFiles /Users/lequan/workspace/xcode/myopencv/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lequan/workspace/xcode/myopencv/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Demo.out

# Build rule for target.
Demo.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Demo.out
.PHONY : Demo.out

# fast build rule for target.
Demo.out/fast:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/build
.PHONY : Demo.out/fast

Demo.o: Demo.cpp.o
.PHONY : Demo.o

# target to build an object file
Demo.cpp.o:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/Demo.cpp.o
.PHONY : Demo.cpp.o

Demo.i: Demo.cpp.i
.PHONY : Demo.i

# target to preprocess a source file
Demo.cpp.i:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/Demo.cpp.i
.PHONY : Demo.cpp.i

Demo.s: Demo.cpp.s
.PHONY : Demo.s

# target to generate assembly for a file
Demo.cpp.s:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/Demo.cpp.s
.PHONY : Demo.cpp.s

LBFRegressor.o: LBFRegressor.cpp.o
.PHONY : LBFRegressor.o

# target to build an object file
LBFRegressor.cpp.o:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/LBFRegressor.cpp.o
.PHONY : LBFRegressor.cpp.o

LBFRegressor.i: LBFRegressor.cpp.i
.PHONY : LBFRegressor.i

# target to preprocess a source file
LBFRegressor.cpp.i:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/LBFRegressor.cpp.i
.PHONY : LBFRegressor.cpp.i

LBFRegressor.s: LBFRegressor.cpp.s
.PHONY : LBFRegressor.s

# target to generate assembly for a file
LBFRegressor.cpp.s:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/LBFRegressor.cpp.s
.PHONY : LBFRegressor.cpp.s

RandomForest.o: RandomForest.cpp.o
.PHONY : RandomForest.o

# target to build an object file
RandomForest.cpp.o:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/RandomForest.cpp.o
.PHONY : RandomForest.cpp.o

RandomForest.i: RandomForest.cpp.i
.PHONY : RandomForest.i

# target to preprocess a source file
RandomForest.cpp.i:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/RandomForest.cpp.i
.PHONY : RandomForest.cpp.i

RandomForest.s: RandomForest.cpp.s
.PHONY : RandomForest.s

# target to generate assembly for a file
RandomForest.cpp.s:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/RandomForest.cpp.s
.PHONY : RandomForest.cpp.s

TestDemo.o: TestDemo.cpp.o
.PHONY : TestDemo.o

# target to build an object file
TestDemo.cpp.o:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/TestDemo.cpp.o
.PHONY : TestDemo.cpp.o

TestDemo.i: TestDemo.cpp.i
.PHONY : TestDemo.i

# target to preprocess a source file
TestDemo.cpp.i:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/TestDemo.cpp.i
.PHONY : TestDemo.cpp.i

TestDemo.s: TestDemo.cpp.s
.PHONY : TestDemo.s

# target to generate assembly for a file
TestDemo.cpp.s:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/TestDemo.cpp.s
.PHONY : TestDemo.cpp.s

TrainDemo.o: TrainDemo.cpp.o
.PHONY : TrainDemo.o

# target to build an object file
TrainDemo.cpp.o:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/TrainDemo.cpp.o
.PHONY : TrainDemo.cpp.o

TrainDemo.i: TrainDemo.cpp.i
.PHONY : TrainDemo.i

# target to preprocess a source file
TrainDemo.cpp.i:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/TrainDemo.cpp.i
.PHONY : TrainDemo.cpp.i

TrainDemo.s: TrainDemo.cpp.s
.PHONY : TrainDemo.s

# target to generate assembly for a file
TrainDemo.cpp.s:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/TrainDemo.cpp.s
.PHONY : TrainDemo.cpp.s

Tree.o: Tree.cpp.o
.PHONY : Tree.o

# target to build an object file
Tree.cpp.o:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/Tree.cpp.o
.PHONY : Tree.cpp.o

Tree.i: Tree.cpp.i
.PHONY : Tree.i

# target to preprocess a source file
Tree.cpp.i:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/Tree.cpp.i
.PHONY : Tree.cpp.i

Tree.s: Tree.cpp.s
.PHONY : Tree.s

# target to generate assembly for a file
Tree.cpp.s:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/Tree.cpp.s
.PHONY : Tree.cpp.s

Utils.o: Utils.cpp.o
.PHONY : Utils.o

# target to build an object file
Utils.cpp.o:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/Utils.cpp.o
.PHONY : Utils.cpp.o

Utils.i: Utils.cpp.i
.PHONY : Utils.i

# target to preprocess a source file
Utils.cpp.i:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/Utils.cpp.i
.PHONY : Utils.cpp.i

Utils.s: Utils.cpp.s
.PHONY : Utils.s

# target to generate assembly for a file
Utils.cpp.s:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/Utils.cpp.s
.PHONY : Utils.cpp.s

liblinear/linear.o: liblinear/linear.cpp.o
.PHONY : liblinear/linear.o

# target to build an object file
liblinear/linear.cpp.o:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/liblinear/linear.cpp.o
.PHONY : liblinear/linear.cpp.o

liblinear/linear.i: liblinear/linear.cpp.i
.PHONY : liblinear/linear.i

# target to preprocess a source file
liblinear/linear.cpp.i:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/liblinear/linear.cpp.i
.PHONY : liblinear/linear.cpp.i

liblinear/linear.s: liblinear/linear.cpp.s
.PHONY : liblinear/linear.s

# target to generate assembly for a file
liblinear/linear.cpp.s:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/liblinear/linear.cpp.s
.PHONY : liblinear/linear.cpp.s

liblinear/tron.o: liblinear/tron.cpp.o
.PHONY : liblinear/tron.o

# target to build an object file
liblinear/tron.cpp.o:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/liblinear/tron.cpp.o
.PHONY : liblinear/tron.cpp.o

liblinear/tron.i: liblinear/tron.cpp.i
.PHONY : liblinear/tron.i

# target to preprocess a source file
liblinear/tron.cpp.i:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/liblinear/tron.cpp.i
.PHONY : liblinear/tron.cpp.i

liblinear/tron.s: liblinear/tron.cpp.s
.PHONY : liblinear/tron.s

# target to generate assembly for a file
liblinear/tron.cpp.s:
	$(MAKE) -f CMakeFiles/Demo.out.dir/build.make CMakeFiles/Demo.out.dir/liblinear/tron.cpp.s
.PHONY : liblinear/tron.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Demo.out"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Demo.o"
	@echo "... Demo.i"
	@echo "... Demo.s"
	@echo "... LBFRegressor.o"
	@echo "... LBFRegressor.i"
	@echo "... LBFRegressor.s"
	@echo "... RandomForest.o"
	@echo "... RandomForest.i"
	@echo "... RandomForest.s"
	@echo "... TestDemo.o"
	@echo "... TestDemo.i"
	@echo "... TestDemo.s"
	@echo "... TrainDemo.o"
	@echo "... TrainDemo.i"
	@echo "... TrainDemo.s"
	@echo "... Tree.o"
	@echo "... Tree.i"
	@echo "... Tree.s"
	@echo "... Utils.o"
	@echo "... Utils.i"
	@echo "... Utils.s"
	@echo "... liblinear/linear.o"
	@echo "... liblinear/linear.i"
	@echo "... liblinear/linear.s"
	@echo "... liblinear/tron.o"
	@echo "... liblinear/tron.i"
	@echo "... liblinear/tron.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

